### ISSUE TITLE
iamtesch/pid-refactor Gazebo Segmentation fault

### ISSUE THREAD

**Issue by josephcoombe** [HebiRobotics/HEBI-ROS#120]
> ...
> Thread 37 "gzserver" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fff3affd700 (LWP 4344)]
> 0x00007fff38dbb967 in hebiros::sim::PidController::update(double, double, double, hebiros::PidGainsMsg_<std::allocator<void> > const&, unsigned long) ()
>    from /home/joseph/tto-robotics/behavior_library_catkin_ws/catkin_ws/devel/lib/libhebiros_gazebo_plugin.so
> (gdb)

**Comment by iamtesch** [comment]
This should be fixed now -- sorry!
