### ISSUE TITLE
Support full commands available in C++ API

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/HEBI-ROS#31]
* The feedback coming from modules is broken into two message types you can subscribe to - the  `/hebiros/<group>/feedback/joint_state` message, which just provides position/velocity/effort, and the `/hebiros/<group>/feedback` message, which provides all available actuator feedback.

* We have a `/hebiros/<group>/command/joint_state` message that parallels the feedback/joint_state one, but do not subscribe to a `/hebiros/<group>/command` topic.  We could add this topic to support the full complement of commands available to send to the module, including gains.

* Additionally, for gains it is especially important to ensure you have confirmation that these gains were set (if you are just sending once at the start of a script as opposed to continuously changing the gains).  We could also add a service based on this same "full command" message that returns an acknowledgement, to parallel the C++ `Group::sendCommandWithAcknowledgement`.

Thoughts?  Currently, there is no way to set gains through the ROS API, and a customer is hoping to use this in the near future.

Loading/saving gains from an XML file may be easy to implement as well (just adding services for the read/write that accept a file path string) -- if we can do this as well, this would be awesome.

**Comment by xaxafour** [comment]
That sounds fine.  I don't see any issues in using the service as an additional command option, just needs to be tested.

Would it be okay to use a YAML file for loading the gains as parameters instead?  This is already a standard procedure in ROS.

**Comment by iamtesch** [comment]
Cool -- I think this will be relatively straightforward.  I'll sketch out the proposed full command message tomorrow so we have something concrete to work from.

The XML load/save is already supported in the C++ API (and writes to the same format used by MATLAB and SCOPE), so that's why I was suggesting that path forward.  I don't know anything about the ROS YAML loading, though -- I'm interested in learning more about that.  I'd say let's punt on the file-based gains for now, though, and get the message-based support in and tested first.

**Comment by iamtesch** [comment]
Here's a proposed (set of) messages for the "full command".  This covers the elements of the C++ API which are commonly used, and we can get smaller tweaks in later (e.g., setting LED color or IO pins) after this stabilizes in the underlying API.

I suggest breaking this up hierarchically to avoid the 42 lines just for the PID gains.  Also, having the "settings" separately I think makes the usage a little clearer (these are the items you can set and save on the module), and eliminates the naming collision with "name".

Thoughts/feedback welcome -- I'm not married to these particular choices if there is a better way to do things.

==================
FullCommandMsg.msg
==================

string name[]
hebiros/SettingsMsg settings
float64 position[]
float64 velocity[]
float64 effort[]

==================
Settings.msg
==================
int CONTROL_STRATEGY_OFF = 0
int CONTROL_STRATEGY_DIRECT_PWM = 1
int CONTROL_STRATEGY_2 = 2
int CONTROL_STRATEGY_3 = 3
int CONTROL_STRATEGY_4 = 4

hebiros/PidGainsMsg position_gains
hebiros/PidGainsMsg velocity_gains
hebiros/PidGainsMsg effort_gains
// Note -- this should be set to one of the values above!
int control_strategy[]
string name[]
string family[]
bool save_current_settings[]

==================
PidGains.msg
==================
float64 kp[]
float64 ki[]
float64 kd[]
float64 feed_forward[]
float64 dead_zone[]
float64 i_clamp[]
float64 punch[]
float64 min_target[]
float64 max_target[]
float64 target_lowpass[]
float64 min_output[]
float64 max_output[]
float64 output_lowpass[]
bool d_on_error[]

**Comment by xaxafour** [comment]
#34
