### ISSUE TITLE
getGroupFromNames fix

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/HEBI-ROS#32]
Small bug found in getGroupFromNames -- if you have multiple families and names, it tries to look up a module for each combination of these.  so:

{HEBI_A, HEBI_B}
{arm, shoulder}

should give 

HEBI_A | arm
HEBI_B | shoulder

but right now gives

HEBI_A | arm
HEBI_A | shoulder
HEBI_B | arm
HEBI_B | shoulder

**Comment by xaxafour** [comment]
#54
