### ISSUE TITLE
Gazebo Plugin: joint_state not published to /hebiros/mygroup/feedback/joint_state ROS Topic unless Trajectory being executed

### ISSUE THREAD

**Issue by josephcoombe** [HebiRobotics/HEBI-ROS#57]
Sorry for the delay. I’m going to be sending you guys some more info on Gazebo Simulation (based on our experiences with it)!

I got the chance to test out this Gazebo Plugin example:
```
roslaunch hebiros_advanced_examples x_demo_gazebo_setup.launch
roslaunch hebiros hebiros_gazebo.launch
rosrun hebiros_basic_examples example_04_trajectory_node
```
Very nice! It looks good.

---

Question for you. One of my nodes (that previously worked in real-world) did not work with the new HEBI Gazebo Plugin.

When I looked into it, the cause was that my node was waiting to get the robot’s initial joint state via the `/hebiros/mygroup/feedback/joint_state` ROS Topic.

Going back to your Gazebo Plugin example, I noticed that when simulating, the current joint_state is only published to `/hebiros/mygroup/feedback/joint_state` when the `example_04_trajectory_node` is executing a trajectory.

(`$ rostopic  echo /hebiros/mygroup/feedback/joint_state`)

**Comment by xaxafour** [comment]
Feedback was not available until commanded.  Feedback is now available upon group creation in #63
