### ISSUE TITLE
xacro templates have unrealistic inertial matrices

### ISSUE THREAD

**Issue by josephcoombe** [HebiRobotics/HEBI-ROS#58]
Fyi, the xacro template files [here](https://github.com/HebiRobotics/HEBI-ROS/tree/master/hebiros_description/urdf) have quite large (unity) inertial matrices.

Gazebo:
![no_inertia](https://user-images.githubusercontent.com/12258096/37121972-75088a68-2224-11e8-82c1-9fb816c475ce.png)

Viewing inertia tensors (with original masses - see: http://gazebosim.org/tutorials?tut=inertia#CheckinginGazebo):
![yes_inertia](https://user-images.githubusercontent.com/12258096/37122042-9fd42090-2224-11e8-8eb8-a9b19b983d02.png)

**Comment by iamtesch** [comment]
This should be resolved by #69 -- after this is tested/approved/merged in, we can close this
