### ISSUE TITLE
linux_i686 Architecture  libhebi.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by AdamPettinger** [HebiRobotics/HEBI-ROS#82]
I've been doing most of my development on a linux_x86_64 desktop, but I am moving to a laptop that is i686. I cloned the HEBI-ROS repo, changed hebiros/CMakeLists.txt to target the i686 library, and tried to build. I got the following error:

```
Errors     << hebiros:make /home/adamp/catkin_ws/logs/hebiros/build.make.000.log                                                        
/home/adamp/catkin_ws/src/HEBI-ROS/hebiros/lib/linux_i686/libhebi.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [/home/adamp/catkin_ws/devel/.private/hebiros/lib/hebiros/hebiros_node] Error 1
make[1]: *** [CMakeFiles/hebiros_node.dir/all] Error 2
make: *** [all] Error 2
```

I went back to the last commit where hebiros/lib/linux_i686/libhebi.so changed (commit bbd824b), checked it out and build the hebiros package just fine. Just for clarity for both versions, I changed the hebiros/CMakeLists.txt from

`target_link_libraries(hebiros_node ${catkin_LIBRARIES} ${PROJECT_SOURCE_DIR}/lib/linux_x86_64/libhebi.so)`

to

`target_link_libraries(hebiros_node ${catkin_LIBRARIES} ${PROJECT_SOURCE_DIR}/lib/linux_i686/libhebi.so)`

**Comment by iamtesch** [comment]
Thanks for the heads up -- we can verify this file is an x64 file.  We're working on patching this up now.

**Comment by iamtesch** [comment]
When you get a chance, could you check out PR #83? If this addresses your issue, I'll merge that into master and back into develop as well.

Sorry for the trouble here, and thanks for reaching out.

**Comment by AdamPettinger** [comment]
That fix built as expected and everything is working.

Thanks for looking at this quickly!
